// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHub.Models;

#nullable disable

namespace SmartHub.Models.Migrations
{
    [DbContext(typeof(SmartHubDbContext))]
    [Migration("20260616093113_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SmartHub.Models.IoTDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("IoTDevices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A smart light bulb.",
                            IsOn = true,
                            Name = "Smart Light",
                            Value = 75.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "A smart thermostat for home heating.",
                            IsOn = false,
                            Name = "Smart Thermostat",
                            Value = 22.5
                        },
                        new
                        {
                            Id = 3,
                            Description = "A smart plug to control appliances.",
                            IsOn = true,
                            Name = "Smart Plug",
                            Value = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
